const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const MAIN_SCREEN_BEST_POPULAR_MOVIE_AND_SERIALS="BEST POPULAR MOVIES AND SERIALS";
const SHOW_CASES_TITLE="SHOWCASES";
const SHOW_CASES_SEE_MORE="MORE SHOWCASES";
const BEST_ACTOR_TITLE="BEST ACTORS";
const BEST_ACTOR_SEE_MORE="MORE ACTORS";
const MAIN_SCREEN_CHECK_MOVIE_SHOWTIMES ="Check Movie\nShowtimes";
const MAIN_SCREEN_SEE_MORE="SEE MORE";

const MOVIE_DETAILS_SCREEN_ACTORS_TITLE="ACTORS";
const MOVIE_DETAILS_SCREEN_CREATORS_TITLE="CREATORS";
const MOVIE_DETAILS_SCREEN_CREATORS_SEE_MORE="MORE CREATORS";
const MOVIE_DETAILS_STORYLINE_TITLE="STORYLINE";
const MOVIE_DETAILS_SCREEN_RELATED_MOVIES="Related Movies";
